	scopeName "_FNCSCOPE_";
	params ["___obj___"];
		private ["_house", "_pos", "_unitClassName", "_unit"];
	_house = ((___obj___ select 5) select ( (floor ( (random ( (count (___obj___ select 5)) )) )) ));
	_pos = ([] call {private "___tmp___"; ___tmp___ = (_house); ___tmp___ = (___tmp___ getVariable ( "positions" )); ___tmp___});
	_unitClassName = (GVAR_GVARS_unitClasses select ( (floor ( (random ( ((count GVAR_GVARS_unitClasses) - 1) )) )) ));
	_unit = (( (GVAR_GVARS_missionGroup) ) createUnit [ (_unitClassName) , (_pos select ( (floor ( (random ( (count _pos) )) )) )) , [ ] , 0 , "FORM" ]);
	doStop ((_unit));
		[] call {private "___tmp___"; ___tmp___ = (_unit); ___tmp___ = (___tmp___ setVariable [ "owner" , (getPlayerUID ((player))) , true ]);};
	((_unit)) addEventHandler ["Killed", (((missionNamespace)) getVariable (("X39_Insurgency_Square_fnc_EH_Killed")))];
	((_unit)) setVariable ["KillTime", -1, true];
		[___obj___, 1] call X39_Insurgency_Square_fnc_addUnitCount;
		[___obj___, (_unit)] call X39_Insurgency_Square_fnc_addToLocalUnits;
